INSERT INTO BOOK (title, author, price) VALUES ('THE HOUSEMAID IS WATCHING','MCFADDEN, FREIDA', 45);
INSERT INTO Book (title, author, price) VALUES ('ERUPTION','CRICHTON, MICHAEL', 50);
INSERT INTO Book (title, author, price) VALUES ('SWAN SONG','HILDERBRAND, ELIN', 38);
INSERT INTO Book (title, author, price) VALUES ('DAD, I WANT TO HEAR YOUR STORY','MASON, JEFFREY',42);
INSERT INTO Book (title, author, price) VALUES ('THE WOMEN','HANNAH, KRISTIN',65);
INSERT INTO Book (title, author, price) VALUES ('THE HOUSEMAID','MCFADDEN, FREIDA',40);
INSERT INTO Book (title, author, price) VALUES ('A COURT OF THORNS AND ROSES','MAAS, SARAH J.', 40);
INSERT INTO Book (title, author, price) VALUES ('CAMINO GHOSTS','GRISHAM, JOHN', 65);
INSERT INTO Book (title, author, price) VALUES ('RECKIESS THE POWERIESS TRILOGY','NADIR, AL M.', 45);
INSERT INTO Book (title, author, price) VALUES ('DOG MAN: THE SCARLET SHEDDER','PILKEY, DAV', 30);

